### ISSUE TITLE
Having an issue with my embed. 

### ISSUE THREAD

**Issue by OmiMike** [gazmull/discord-paginationembed#10]
Getting an error with a few of my commands just updated to the newest version 11 i am guessing. 

![image](https://user-images.githubusercontent.com/39207164/42130481-90719fa2-7cb4-11e8-824a-ce5288a6893a.png)

I havent been able to figure out how to fix it yet

**Comment by gazmull** [comment]
Hi. I've tested v11 branch and there are no problems encountered with my test script. Perhaps showing your source code will help?

**Comment by OmiMike** [comment]
```const Discord = require('discord.js');
const { Embeds: EmbedsMode, FieldsEmbed: FieldsEmbedMode } = require('discord-paginationembed');
module.exports = {
	name: 'pokemon',
	aliases: ['p'],
	description: 'Pokemon List',
	cooldown: 1,
	async execute(prefix, command, message, args, db) {
		db.query("SELECT *, user_monsters.ID  FROM user_monsters JOIN monsters ON user_monsters.monster_ID = monsters.ID WHERE user_ID='" + message.author.id + "' ORDER BY seq_num;",async function(err,rows){
			if(err) throw err;
			if(rows != null && rows.length > 0){
				var pagenum = 1;
				if(!isNaN(parseInt(args[0]))) pagenum = args[0];
				var pages = [];
				var listpage = '';
				rows.forEach((row) => {
					var iv = (Math.floor(((row.attiv + row.defiv + row.hpiv + row.speediv + row.spattiv + row.spdefiv) / 6) * 100));
					var pokerow = (row.shiny != 1 ? '' : '__✨__ ') + '# '  + row.seq_num + ' **' + row.name + '** | IV: ' + iv + '% | Lvl: ' + Math.floor((1/58) * (Math.sqrt(29) * Math.sqrt(8 * row.xp + 29) - 29)) + '\n';
					if((pokerow.length + listpage.length) > 725){
						pages.push(listpage);
						listpage = pokerow;
					}else{
						listpage += pokerow;
					}
				});
				pages.push(listpage);
				if(pagenum > pages.length) pagenum = 1;
				const embeds = [];
				var i = 0;
				pages.forEach((page) => {
					i++;
					const exampleEmbed = new Discord.MessageEmbed()
					.setThumbnail(message.author.displayAvatarURL)
					.setColor('#0099ff')
					.setTitle(message.author.username + '\'s Pokemon')
					.addField('Pokemon List', pages[i - 1])
					.setFooter("Showing page " + i + " of " + pages.length + ". Use `" + prefix + command + " <number>` to show a new page or use the emojis below.");
					embeds.push(exampleEmbed);
				});
				var neb = new EmbedsMode().setArray(embeds)
				  .setAuthorizedUser(message.author)
				  .setClientMessage(null, message.author.toString())
				  .setChannel(message.channel)
				  .showPageIndicator(false)
				  .setPage(pagenum)
				  .setColor(3447003);
				return await neb.build();
				///node_modules/discord.js/src/structures/MessageEmbed.js:157if (value.length > 1024) throw new RangeError('MessageEmbed field values may not exceed 1024 characters.');
			}else{
				message.reply("You don't have any pokemon!");
			}
		});
	}
};
```

This is one of my commands i think fixing this one I will be able to do the rest because they are basically the same setup.. I have tried putting in the RichEmbed and that isnt working either @gazmull

**Comment by OmiMike** [comment]
now getting a new error for RichEmbed

![image](https://user-images.githubusercontent.com/39207164/42134655-424b8068-7d0e-11e8-9414-87ec9f5e6eee.png)

Even after adding the RichEmbed it still likes to play with me hahaha

**Comment by gazmull** [comment]
I missed the opportunity to ask this: What Discord.JS version are you using? I can only assume right now [according to the source code] that you're using the master version (v12) of D.JS, which installing `v11` branch is not an option and instead install the master branch. Also recently, `.setAuthorizedUser(<user>)` has been changed to `.setAuthorizedUsers(<array of user ids>)` at master branch.

For more change notes: [Click me](https://github.com/gazmull/discord-paginationembed/compare/fe1ba10...be04af8) or refer to [the updated docs](https://gazmull.github.io/discord-paginationembed)

**Comment by OmiMike** [comment]
So the master branch would be which npm install.. We use node.js

**Comment by OmiMike** [comment]
npm install gazmull/discord-paginationembed#v11

Is this not the one i should be using?

**Comment by gazmull** [comment]
Yes. `gazmull/discord-paginationembed#v11` is only for D.JS 11.3.2 and below.

**Comment by OmiMike** [comment]
Thats the one i have and its throwing the RichEmbed error

**Comment by gazmull** [comment]
Are you sure your D.JS Version is v11.3.2 or below? It seems your source code says otherwise with `new Discord.MessageEmbed()`— or do you happen to really use `MessageEmbed` instead of `RichEmbed` for declaring a new instance of an embed?

The only thing I could think of, if ever the question above doesn't solve anything, is re-installing Discord.JS.

**Comment by OmiMike** [comment]
MessageEmbed is whats used on all my commands and I'm not sure which version I'm using for discord.js to be honest

**Comment by OmiMike** [comment]
I download discord.js about 6 weeks ago

**Comment by gazmull** [comment]
Please refer to `npm ls discord.js`.
