### ISSUE TITLE
Disabling the navigation emoji, and overriding with functionEmojis calls menu function not callback

### ISSUE THREAD

**Issue by KyleBoyer** [gazmull/discord-paginationembed#18]
```
.addFunctionEmoji('🗑', async function(user, caller){
	console.log(user.username + " clicked delete.");
	db.query("DELETE FROM ...;");
	caller.clientMessage.delete();
})
.setDisabledNavigationEmojis(['all'])
```

The above code will not properly call the callback, instead it will just delete the client message.

**Comment by KyleBoyer** [comment]
@gazmull To think about it, I could work with an onDelete callback too, for both timeout, and emoji delete?

**Comment by gazmull** [comment]
Pushed a fix at `patch-1`. Let me know if this resolves the issue.

Regarding the additions of further callbacks, I'm thinking of adding an event emitter for such case to avoid severe littering.

**Comment by gazmull** [comment]
This recently added feature also introduced a bug where having empty array will completely disable the navigation emojis. I will be rewriting the whole feature and possibly another interface changes. Feel free to start working on it, I might not have the time due to exams. 🙆‍♂️ 

ps. patch-1 doesn't fix anything except for the overriding thing.

**Comment by KyleBoyer** [comment]
Sounds good haha! Do you have discord? I wanted to talk to you about code, but some of it is private for competition reasons.

**Comment by KyleBoyer** [comment]
Kyle#9747

**Comment by gazmull** [comment]
Sure thing. Added you with `Euni#0011`

**Comment by gazmull** [comment]
I'm face palming so hard, it was my proposed fix earlier (just similarly) but can't seem to implement the fix properly. Thanks for the fix.

For future concerns regarding navigation emoji's function still overriding the customised function, please disable the navigation emoji first per logical basis.

Now I can rest peacefully... <img src='https://cdn.discordapp.com/emojis/435822456549146625.png' width=24 />
