### ISSUE TITLE
'Prepearing...' still visible after embed is shown

### ISSUE THREAD

**Issue by truelecter** [gazmull/discord-paginationembed#22]
```js
const embeds = hero.forms.map((form, idx, arr) => new MessageEmbed()
        .setTitle(`${translate(form.name)} (${form.star}★)`)
        .setDescription(translate(form.lore))
        .setThumbnail(imageUrl(form.image))
        .setFooter(`Page ${idx + 1}/${arr.length}`)
    );

const msg = new EmbedsMode()
    .setArray(embeds)
    .setAuthorizedUsers([message.author.id])
    .setChannel(message.channel)
    .setPage(page)
    .showPageIndicator(false)
    .setDisabledNavigationEmojis(['JUMP'])
    .setColor(classColors[hero.class])
    .addField('Class', capitalizeFirstLetter(hero.class), true)
    .addField('Type', capitalizeFirstLetter(hero.type), true)
    .addField('Domain', hero.domain ? '-' : '-', true)
    .addField('Gender', capitalizeFirstLetter(hero.gender), true)
    .build();

message.channel
    .send(msg)
    .catch(error => console.log(error));
```
![image](https://user-images.githubusercontent.com/5520406/44468267-7fa41900-a62d-11e8-8a00-fcaba34d00d7.png)

However, if I change in your library code ('src/struct/Embeds.js')
```js 
await this.clientMessage.message.edit(shouldIndicate, { embed: this.currentEmbed });
```
to 
```js 
await this.clientMessage.message.edit(null, { embed: this.currentEmbed });
```
'Prepearing...' caption is removed. 

The problem is that `clientMessage.content` which is used to build `shouldIndicate` is shared with initial message, so if I set it to empty string, space, non breaking space, etc - Discord discards message, because it is treated as empty.

**Comment by truelecter** [comment]
Also, every time initial message sent, I get following error in console: 
![image](https://user-images.githubusercontent.com/5520406/44477995-f6004580-a644-11e8-9d4d-4b1a6a8f1907.png)

**Comment by gazmull** [comment]
Thanks for pointing out this overlooked error in editing the message. I'll be pushing a fix for it today. As for the second issue, this is caused by your `message.channel.send(msg)`. `PaginationEmbed.build()` already sends a message for you upon calling it as demonstrated in the examples, although I believe the method's name shall be changed someday to prevent confusion.

**Comment by truelecter** [comment]
Thanks!
