### ISSUE TITLE
Catch delete errors

### ISSUE THREAD

**Issue by daniellwdb** [gazmull/discord-paginationembed#26]
When people delete a embed before the bot can do it, it returns a Discord API error 'Unknown message', could you return on those errors so they won't appear in the console?

**Comment by gazmull** [comment]
Hi. It should emit an `error` event now. Attach a listener directly at the instance so you can handle the error yourself.

```js
<PaginationEmbed>.on('error', console.error)
```

This is currently available at *master branch* (will push it to a new version once this issue has been resolved— please verify): `npm i gazmull/discord-paginationembed`

**Comment by daniellwdb** [comment]
> Hi. It should emit an `error` event now. Attach a listener directly at the instance so you can handle the error yourself.
> 
> ```js
> <PaginationEmbed>.on('error', console.error)
> ```
> 
> This is currently available at _master branch_ (will push it to a new version once this issue has been resolved— please verify): `npm i gazmull/discord-paginationembed`

It looks like only the changelog, readme etc gets downloaded when running the command
