### ISSUE TITLE
t.users.last is not a function

### ISSUE THREAD

**Issue by Androz2091** [gazmull/discord-paginationembed#35]
Here is my code:
```js
const { lastPosts } = await this.client.insta.getProfile(this.client.config.insta);
const lastPostShortCode = lastPosts[0].shortcode;
const lastPost = await this.client.insta.getPost(lastPostShortCode);
const embeds = [];

lastPost.contents.forEach((item) => {
    const embed = new Discord.MessageEmbed()
    .setImage(item.url);
    embeds.push(embed);
});

let pagination = new Pagination.Embeds()
.setArray(embeds)
.setAuthorizedUsers([message.author.id])
.setChannel(message.channel)
.setPageIndicator(true)
.setColor("#FF0000")
.setTitle("Ouvrir sur Instagram")
.setURL(lastPosts[0].link)
.addField("❤️ Likes", lastPost.likes)
.addField("💬 Commentaires", lastPosts[0].comments);

pagination.build();
```
The `embeds` var contains an Array of MessageEmbeds. When I react, all the reactions are removed without error.

I added a `console.log(t);` at the top of the `_cleanUp` function, and now I'm getting this error:
```
TypeError: t.users.last is not a function
    at exports.Embeds._awaitResponse (/Users/simon/Documents/GitHub/cyanide-happiness-bot/node_modules/discord-paginationembed/bin/base/index.js:163:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
<img width="457" alt="Capture d’écran 2020-02-14 à 10 36 38" src="https://user-images.githubusercontent.com/42497995/74519425-f31ea200-4f15-11ea-8a3f-e993442e7330.png">

**Comment by gazmull** [comment]
Deployed fix for the error. Please reinstall with `npm i discord-paginationembed@beta`!

---

Since it was caught by the internal function, the error got emitted through `error` event (PaginationEmbed extends [EventEmitter](https://nodejs.org/api/events.html#events_class_eventemitter)). I advise listening to the event to recognise the cause of the problem right away. Thanks for reporting!

**Comment by Jovin-Ang** [comment]
I am still running into this issue with the latest version
```
TypeError: Cannot read property 'last' of undefined
    at exports.Embeds._awaitResponse (/rbd/pnpm-volume/62876d80-160e-479c-88ac-d013b13a516d/node_modules/.registry.npmjs.org/discord-paginationembed/2.0.0-beta.4/node_modules/discord-paginationembed/bin/base/index.js:163:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Androz2091** [comment]
Hmm... It worked for me.
