### ISSUE TITLE
Regarding the issue of RichEmbeds and attachments.

### ISSUE THREAD

**Issue by Dragonflares** [gazmull/discord-paginationembed#37]
Hey

So I've been trying to use an array of embeds, but instead of message embeds, a Rich Embed array, because I needed images to pop up.

![](https://cdn.discordapp.com/attachments/402150235071184918/685225391517990952/unknown.png)

And like, the first image went well, but the second one...

![](https://cdn.discordapp.com/attachments/402150235071184918/685225535642665026/unknown.png)

Why is this a thing?
Here's the code btw:

 `async function techInformation(message, CorpMember) {
    const messagesplit = message.content.split(" ")

    let embeds = []
    
    for(let tech in TechData) {
        let Embed = new RichEmbed().setColor("RANDOM")
        Embed.setTitle(`${tech}`)
        Embed.attachFile(`techIcons/${tech}.png`)
        Embed.setThumbnail(`attachment://${tech}.png`)
        embeds.push(Embed)
    }
    let iptech = new Pagination.Embeds()
        .setArray(embeds)
        .setAuthorizedUsers([message.author.id])
        .setChannel(message.channel)
        .setPageIndicator(true)
        .setTitle(`Interactive Tech System for ${message.author.username}`)
        .setColor("RANDOM")
        .setDisabledNavigationEmojis(['DELETE'])
        .build()
}
`

This is on 11.5.1

**Comment by gazmull** [comment]
Hi,

That is how attachments work (When the attachment is not used by the embed, it changes to a regular attachment) and unfortunately there is nothing the library and the utility can do about that. However if you set an image/thumbnail as a URL, it shouldn't be a problem.

**Comment by Dragonflares** [comment]
Hey,

But then, how do I attach the image that is on my own computer?

**Comment by gazmull** [comment]
In your case, what you want is not an attachment but a URL that can be resolved by Discord (e.g. image hosting sites).

**Comment by Dragonflares** [comment]
Okay, but that explains why it is left up there, but not why it didn't load up the title of the embed inside the embed or the next attachment

**Comment by gazmull** [comment]
Because you are overriding it with the "global" methods:
```js
let embeds = []

for(let tech in TechData) {
    let Embed = new RichEmbed().setColor("RANDOM")
    Embed.setTitle(`${tech}`)
    Embed.attachFile(`techIcons/${tech}.png`)
    Embed.setThumbnail(`attachment://${tech}.png`)
    embeds.push(Embed)
}
let iptech = new Pagination.Embeds()
    .setArray(embeds)
    .setAuthorizedUsers([message.author.id])
    .setChannel(message.channel)
    .setPageIndicator(true)
    .setTitle(`Interactive Tech System for ${message.author.username}`) // This
    .setColor("RANDOM") // and this are methods for customising *all* embeds in the array
    .setDisabledNavigationEmojis(['DELETE'])
    .build()
```

**Comment by Dragonflares** [comment]
Which global methods?

**Comment by gazmull** [comment]
My bad for late reply but those lines with a comment are the global methods I refer to

**Comment by Dragonflares** [comment]
![image](https://user-images.githubusercontent.com/28828524/76168917-7f596900-6152-11ea-92bb-f0e96be59e7b.png)

Ok, so I managed to do it this time, but now images don't load at all. I've put them on imgur, and the link is pasted correctly (it traces you to the image if you go to "open original")

**Comment by Dragonflares** [comment]
nevermind, fixed it, thanks for the help!
