### ISSUE TITLE
Method showPageIndicator() Has No Effect

### ISSUE THREAD

**Issue by dhkatz** [gazmull/discord-paginationembed#4]
```js
new paginator.Embeds()
    .setArray(embeds)
    .setAuthorizedUser(message.author)
    .setChannel(message.channel)
    .showPageIndicator(false)
    .build();
```
Even it I put false explicitly or leave it out the page indication still seems to show.

This seems to be because in `Embeds` you check for `this.showPageIndicator`.

https://github.com/gazmull/discord-paginationembed/blob/07613fea574da818a77f1d2c70dd72a8f0428368/src/struct/Embeds.js#L395

But in `PaginationEmbed`, `showPageIndicator()` is actually setting `this.pageIndicator`

https://github.com/gazmull/discord-paginationembed/blob/07613fea574da818a77f1d2c70dd72a8f0428368/src/struct/base/PaginationEmbed.js#L212

**Comment by KyleBoyer** [comment]
Solved by PR #7

**Comment by dhkatz** [comment]
Many thanks

**Comment by dhkatz** [comment]
Also, I noticed when there is only one page the page number shows as null

Edit: Didn't actually read the PR, noticed you changed that too

**Comment by gazmull** [comment]
This bug has been fixed by the latest push on v11 branch (I assume you're using v11 branch based on the source code you have written above). Thanks to both of you!

**Comment by propaneko** [comment]
Sorry for opening again this old issue, but the situation is actually the same as before, when there is only one page it shows `null` and `.setPageIndicator()` doesnt seem to work. Im on 1.0.1 version of your plugin and 11.5.1 of discord.js.

**Comment by gazmull** [comment]
@ProPanek Hello. Thanks for the heads up. I'll re-open this issue until it's verified and fixed.

**Comment by gazmull** [comment]
Fix pushed to NPM. (version 1.0.2)
