### ISSUE TITLE
Jump message edit Error

### ISSUE THREAD

**Issue by Drelaky** [gazmull/discord-paginationembed#43]
IF ![image](https://user-images.githubusercontent.com/53569746/89830995-6c155400-db5d-11ea-8f22-b7dba510d008.png)

**Error:**
 `(node:7684) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
 at RequestHandler.execute (C:\Users\Drelaky\Desktop\bot2\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
 at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**IF**
![image](https://user-images.githubusercontent.com/53569746/89831263-d4fccc00-db5d-11ea-90bc-afe0ea2928f7.png)
What is the problem???
please help meee

**Comment by Drelaky** [comment]
2error: 
`(node:6824) UnhandledPromiseRejectionWarning: TypeError: this.clientAssets.message.edit is not a function
    at exports.Embeds._loadList (C:\Users\Drelaky\Desktop\bot2\node_modules\discord-paginationembed\bin\Embeds.js:98:128)
    at exports.Embeds.build (C:\Users\Drelaky\Desktop\bot2\node_modules\discord-paginationembed\bin\Embeds.js:28:71)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by gazmull** [comment]
You need to make sure message exists. Also please show the whole code.

**Comment by Drelaky** [comment]
![image](https://user-images.githubusercontent.com/53569746/89880719-d7464100-dbc4-11ea-85db-259ab6a3d77d.png)
![image](https://user-images.githubusercontent.com/53569746/89880745-e0cfa900-dbc4-11ea-829c-3833352204fe.png)
![image](https://user-images.githubusercontent.com/53569746/89880778-ec22d480-dbc4-11ea-8327-6e1bfb62c71a.png)

**Comment by Drelaky** [comment]
I would edit the jump text
![image](https://user-images.githubusercontent.com/53569746/89881484-dd88ed00-dbc5-11ea-85ba-d9d26489bf50.png)

**Comment by gazmull** [comment]
My bad I missed the first image. What you should pass to `setClientAssets`'s `message` option is a Message object by the client, not by the user nor a string. Since it's completely optional, you can omit it if you want to send a new message instead of editing a message already sent by the client.

As for editing the jump text, it's the `prompt` option.

Reference:
- [PaginationEmbed.setClientAssets()](https://docs.thegzm.space/discord-paginationembed/stable/classes/paginationembed.html#setclientassets)
- [Interface ClientAssets](https://docs.thegzm.space/discord-paginationembed/stable/interfaces/clientassets.html)
