### ISSUE TITLE
Embed is not showing

### ISSUE THREAD

**Issue by sawa-ko** [gazmull/discord-paginationembed#45]
I try to put a simple test Embed but the result is that in the response of the message there is nothing, the embed does not appear.

```ts
    let embeds = [];
    embeds.push(
      new MessageEmbed().setDescription('xd').setFooter('xd').setTitle('uy'),
    );
    
    try {
      new Pagination.Embeds()
        .setArray(embeds)
        .setAuthorizedUsers(command.author.id)
        .setChannel(command.channel as TextChannel | DMChannel)
        .setPageIndicator(true)
        .setPage(1)
        .setTitle('Test')
        .setDescription(
          'Test',
        )
        .setFooter(EmbedMessageEnum.FOOTER_HELP)
        .setColor(this._embedMessageService.getRandomColor())
        .setThumbnail(Environments.photo)
        .build();
    } catch ({ message }) {
      await command.author.send(
        this._embedMessageService.noPermissionMessage(
          command.guild.channels.cache.get(command.channel.id).name,
        ),
      );
    }
  }
```
> Response

![image](https://user-images.githubusercontent.com/56084970/94494513-98883c80-01ac-11eb-8853-132c052c2eaf.png)

As you can see, the embed that was entered in the array does not appear.

**Comment by gazmull** [comment]
Because the global methods:
```js
new Pagination.Embeds()
  ...
  .setTitle('Test')
  .setDescription(
   'Test',
  )
  .setFooter(EmbedMessageEnum.FOOTER_HELP)
  ...
```
Override what you've set here:
```js
embeds.push(
   new MessageEmbed().setDescription('xd').setFooter('xd').setTitle('uy'),
 );
```

**Comment by sawa-ko** [comment]
Oh, I understand, but why is something not to be done its methods are available in the package constructor?

That's why I didn't realize it because as I saw that I had no problems using those methods in the constructor.

**Comment by gazmull** [comment]
Because it is pretty situational. It's also shown in [examples](https://github.com/gazmull/discord-paginationembed#embeds-mode) on how they work. You never know when you need it.

But I get you, these "global" methods are pretty wonky to work with in your current situation. My only advise is to read the [documentation](https://docs.thegzm.space/discord-paginationembed/master/classes/embeds.html) of this pagination mode for reference.

**Comment by sawa-ko** [comment]
Ok, now it works fine for me, but is there a way to locate the messages? They are in English and I would like to put them in my language.

**Comment by sawa-ko** [comment]
For example, in the text that shows which page the user is on, it appears in English and I see that only the message of jumping to a specified page number can be translated.

**Comment by gazmull** [comment]
It's in the [examples](https://github.com/gazmull/discord-paginationembed#embeds-mode) ([reference](https://docs.thegzm.space/discord-paginationembed/master/classes/paginationembed.html#setclientassets)). Please read the documentation.
