### ISSUE TITLE
I do not know how to change thumbnails for each page, can someone help me out on this?

### ISSUE THREAD

**Issue by siddarthkot** [gazmull/discord-paginationembed#47]

**Comment by gazmull** [comment]
If this is on **Embeds** mode, it's the same as how you would do on a regular embed. Just remember that the array you pass to the instance is an **array of MessageEmbed**.

As for **FieldsEmbed** mode, you can modify it via [`<FieldsEmbed>.embed`](https://docs.thegzm.space/discord-paginationembed/stable/classes/fieldsembed.html#embed) property then you can change it by listening to [`pageUpdate`](https://docs.thegzm.space/discord-paginationembed/stable/classes/paginationembed.html#on) event.
