### ISSUE TITLE
Cannot use Homogeneous Arrays

### ISSUE THREAD

**Issue by andrebrito16** [gazmull/discord-paginationembed#53]
Hi, 

I Have Homogeneous Array like 
`const test = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]`

Can you tell me how to use this on pagination? I Have tried to use example like `.formatField(`LINK`, el => el.(???)`

This just works for arrays that have object inside. 

I want, for example, show just 2 numbers per page passing this on `.setElementsPerPage(2)`

**Comment by sawa-ko** [comment]
Try to do it this way

```ts
const test = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
const FieldsEmbed = new Pagination.FieldsEmbed()
  .setArray(test)
  .setAuthorizedUsers([message.author.id])
  .setChannel(message.channel)
  .formatField('Numbers' , n => n)
  .setElementsPerPage(2);

FieldsEmbed.build();
```

**Comment by andrebrito16** [comment]
Thank you! Worked fine!

Can you help me with another thing?

I Have an API that return two different arrays like links[] and names[]. I`d like to know if it is possible build an embed to show like **CLICK HERE TO 1**, **CLICK HERE TO 2**...

If yes, how can I do this. 

This image shows how can I need. But instead "Test" I need the names that are saved on other array.

![image](https://user-images.githubusercontent.com/30161990/105848951-166f1f80-5fb6-11eb-90bc-151046b8c636.png)

**Comment by d-shaun** [comment]
You could create a new array of objects with both the title and link by looping through the `links` and accessing the value of `names` on the same index or vise versa.
```JS
const names = ["DuckDuckGo", "Discord", "GitHub"];
const links = [
  "https://duckduckgo.com",
  "https://discord.com",
  "https://github.com",
];

const names_with_links = names.map((name, i) => ({ name, link: links[i] }));
console.log(names_with_links);
// OUTPUT: [{ name: "DuckDuckGo", link: "https://duckduckgo.com" }, ...];
```

And then modify the function in `.formatField` appropriately.
```JS
const FieldsEmbed = new Pagination.FieldsEmbed()
  .setArray(names_with_links)
  .setChannel(message.channel)
  .formatField("LINK", (elem) => `[CLICK HERE TO ${elem.name}](${elem.link})`); 
  ```
