### ISSUE TITLE
Disabling jump navigation emoji isn't enough to send paginated embed without MANAGE_MESSAGES

### ISSUE THREAD

**Issue by sriRacha21** [gazmull/discord-paginationembed#56]
**Steps to reproduce:**

1. Create Discord channel in server with bot (no `MANAGE_MESSAGES` or `ADMIN` perm) with discord-paginatedembed .
2. Run command that creates a `PaginationEmbed` and builds it. This command should also disable the jump navigation emoji, the only emoji I believe that requires MANAGE_MESSAGE to work properly (since it deletes another user's message). Here's a short sample of some code that would fit this requirement:
```js
const msg = <some Message instance>;

new Pagination.Embeds()
    .setArray([
        new Discord.MessageEmbed().addField('Test 1', 'test 1'),
        new Discord.MessageEmbed().addField('Test 2', 'test 2')
    ])
    .setAuthorizedUsers([msg.author.id])
    .setChannel(msg.channel)
    .setDisabledNavigationEmojis(['jump'])
    .build()
    .catch(err => {
        if (err) msg.channel.send('I do not have the required permissions to create a paginated embed here.');
    });
```

**Expected result:**
Paginated embed successfully builds and sends.

**Actual result:**
Catch code block runs with an error, saying that the client needs MANAGE_MESSAGES permission. However, since the jump navigation emoji is disabled, my understanding is that this permission is no longer required.

**Comment by sriRacha21** [comment]
Is this issue fixed by commit bcf150b9207c3885884f181d343a592bf9247db2 ?

**Comment by gazmull** [comment]
Yes. Expect a version release soon for it. 👌

**Comment by sriRacha21** [comment]
I don't mean to rush you but it's been 3 months. I'm not quite sure what you meant by "soon"?

**Comment by gazmull** [comment]
Soon™'d. My bad about the broken promise, but I'm pretty busy with unexpected in real life problems that prevents me from reviewing the changes in the upcoming version and some commits I've yet to push but that's something for later I guess.
