### ISSUE TITLE
Change the jump message

### ISSUE THREAD

**Issue by Toskan4134** [gazmull/discord-paginationembed#64]
I want to change the Jump message to other languages, (spanish in this case)
How could I?

**Comment by gazmull** [comment]
It is possible with [`<PaginationEmbed>.setClientAssets()`](https://docs.thegzm.space/discord-paginationembed/stable/classes/paginationembed.html#setclientassets)'s [`prompt`](https://docs.thegzm.space/discord-paginationembed/stable/interfaces/clientassets.html) option:
```js
<PaginationEmbed>.setClientAssets({ prompt: 'wat page' });
```
